version: '3'

services:
    mongodb:
        image: 'mongo'
        ports:
            - '27017-27019:27017-27019'
        volumes: 
            - "./mongo-volume:/data/db"
            - "./ops/db_entrypoint.js:/docker-entrypoint-initdb.d/db_entrypoint.js:ro"
        container_name: wipro-mongodb
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - "./:/app"
        ports:
            - '3000:3000'
        container_name: wipro-node
        depends_on: 
            - mongodb